version: '3.8'

services:
  rd-rating-system:
    build: .
    container_name: rd-rating-system
    ports:
      - "8000:8000"  # vLLM server
      - "8001:8001"  # API server
      - "8501:8501"  # Streamlit app
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./exports:/app/exports
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - GPU_MEMORY_UTILIZATION=0.9
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database service for future use
  # db:
  #   image: postgres:13
  #   container_name: rd-rating-db
  #   environment:
  #     POSTGRES_DB: rd_rating
  #     POSTGRES_USER: rd_user
  #     POSTGRES_PASSWORD: rd_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: 