# HCP Rating System Configuration

# Model Configuration
model:
  name: "mistral-7b-instruct"
  max_length: 4096
  temperature: 0.1
  top_p: 0.9
  load_in_4bit: false
  device_map: "auto"

# Ollama Configuration
ollama:
  base_url: "http://localhost:11434"
  model_name: "mistral"
  temperature: 0.1
  top_p: 0.9
  top_k: 40
  max_tokens: 2048
  timeout: 120

# vLLM Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  tensor_parallel_size: 1
  max_model_len: 8192
  gpu_memory_utilization: 0.9

# Scoring Criteria
scoring:
  dimensions:
    empathy:
      weight: 0.25
      description: "Shows understanding and compassion"
      criteria:
        - "Demonstrates emotional awareness"
        - "Shows genuine concern for patient"
        - "Uses empathetic language"
        - "Validates patient feelings"
    
    clarity:
      weight: 0.25
      description: "Communicates clearly and effectively"
      criteria:
        - "Uses simple, understandable language"
        - "Explains concepts clearly"
        - "Provides structured information"
        - "Confirms patient understanding"
    
    accuracy:
      weight: 0.25
      description: "Provides accurate information and advice"
      criteria:
        - "Gives evidence-based recommendations"
        - "Corrects misconceptions appropriately"
        - "Provides accurate medical information"
        - "Refers to reliable sources"
    
    professionalism:
      weight: 0.25
      description: "Maintains professional standards and boundaries"
      criteria:
        - "Maintains appropriate boundaries"
        - "Shows respect and courtesy"
        - "Follows professional protocols"
        - "Demonstrates ethical behavior"

# Training Configuration
training:
  learning_rate: 2e-4
  num_epochs: 3
  batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 100
  save_steps: 500
  eval_steps: 500
  logging_steps: 10
  
  # LoRA Configuration
  lora:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.1
    bias: "none"
    task_type: "CAUSAL_LM"

# API Configuration
api:
  title: "HCP Rating API"
  description: "API for rating Healthcare Providers based on telehealth transcripts"
  version: "1.0.0"
  docs_url: "/docs"
  redoc_url: "/redoc"
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]

# Frontend Configuration
frontend:
  title: "HCP Rating System"
  description: "AI-powered Healthcare Provider evaluation system"
  page_icon: "🥗"
  layout: "wide"
  theme:
    primaryColor: "#1f77b4"
    backgroundColor: "#ffffff"
    secondaryBackgroundColor: "#f0f2f6"
    textColor: "#262730"

# Data Processing
data:
  max_transcript_length: 4000
  chunk_size: 1000
  overlap: 200
  output_format: "json"
  supported_formats: ["txt", "csv", "json"]
  batch_size: 10

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/hcp_rating.log"

# Export Options
export:
  formats: ["json", "csv", "excel"]
  include_metadata: true
  include_raw_scores: true 